const API_ROUTES = {
  ROOT: "/",
  HEALTH: "/health",
  VERSIONS: {
    v1: "/v1/api"
  },
  GROUPS: "/lims-groups",
  ROLES: "/lims-roles",
  LIMS_USERS: "/lims-users",
  SCHEDULERS: "/lims-schedulers",
  PHRASES: "/lims-phrases",
  CUSTOMERS: "/lims-customers",
  SUPPLIERS: "/lims-suppliers",
  PROJECTS: "/lims-projects",
  STUDIES: "/lims-studies",
  LOCATIONS: "/lims-locations",
  STOCK: "/lims-stocks",
  STOCK_BATCHES: "/lims-stock-batches",
  ALIQUOTS: "/lims-aliquots",
  STOCK_PARAMETERS: "/lims-stock-parameters",
  INSTRUMENTS: "/lims-instruments",
  INSTRUMENT_PARTS: "/lims-instrument-parts",
  CALIBRATION_SCHEDULES: "/lims-calibration-schedules",
  CALIBRATIONS: "/lims-calibrations",
  INSPECTION_PLANS: "/lims-inspection-plans",
  INSPECTION_PERSONNEL: "/lims-inspection-personnel",
  ANALYSES: "/lims-analyses",
  ANALYSIS_COMPONENTS: "/lims-analysis-components",
  TEST_GROUPS: "/lims-test-groups",
  TEST_GROUP_ITEMS: "/lims-test-group-items",
  SPECIFICATIONS: "/lims-specifications",
  SPEC_LIMITS: "/lims-spec-limits",
  BATCHES: "/lims-batches",
  LOTS: "/lims-lots",
  SAMPLES: "/lims-samples",
  TESTS: "/lims-tests",
  TEST_WINDOWS: "/lims-test-windows",
  RESULTS: "/lims-results",
  AUDIT: "/audit",
  PARAMS: "/:id",
  BULK_DELETE: "/bulk-delete",
  RESTORE: "/restore/:id",
  BULK_DUPLICATE: "/bulk-duplicate",
  AUDIT_LOGS: "/:id/audit"
};

export default API_ROUTES;
