import { QueryInterface, DataTypes, Sequelize } from "sequelize";

export const up = async (queryInterface: QueryInterface): Promise<void> => {
  await queryInterface.sequelize.transaction(async (transaction) => {
    await queryInterface.addColumn("lims_groups", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("lims_roles", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("lims_users", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("lims_schedulers", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("phrases", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("phrase_entries", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("customers", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("suppliers", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("projects", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("studies", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("locations", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("stock", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("stock_batches", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("aliquots", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("stock_parameters", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("instruments", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("instrument_parts", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("calibration_schedules", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("calibrations", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("inspection_plans", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("inspection_personnel", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("analyses", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("analysis_components", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("test_groups", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("test_group_items", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("specifications", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("spec_limits", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("batches", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("lots", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("samples", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("tests", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("test_windows", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.addColumn("results", "modified_by", { type: DataTypes.UUID, allowNull: true }, { transaction });
    await queryInterface.renameColumn("customers", "name", "customer_name", { transaction });
    await queryInterface.renameColumn("customers", "contact_email", "email", { transaction });
    await queryInterface.renameColumn("customers", "notes", "description", { transaction });
    await queryInterface.renameColumn("suppliers", "name", "supplier_name", { transaction });
    await queryInterface.renameColumn("suppliers", "contact_email", "email", { transaction });
    await queryInterface.renameColumn("suppliers", "notes", "description", { transaction });
    await queryInterface.renameColumn("projects", "name", "project_id", { transaction });
    await queryInterface.renameColumn("projects", "description", "details", { transaction });
    await queryInterface.renameColumn("locations", "name", "location_name", { transaction });
    await queryInterface.renameColumn("stock", "name", "stock_name", { transaction });
    await queryInterface.renameColumn("instruments", "description", "type", { transaction });
    await queryInterface.renameColumn("instrument_parts", "part_number", "part_id", { transaction });
    await queryInterface.renameColumn("lots", "lot_number", "lot_id", { transaction });
    await queryInterface.renameColumn("samples", "sample_number", "sample_id", { transaction });
    await queryInterface.renameColumn("batches", "batch_number", "batch_id", { transaction });
    await queryInterface.renameColumn("studies", "description", "details", { transaction });
    await queryInterface.addColumn("calibrations", "status", { type: DataTypes.STRING(50), allowNull: true }, { transaction });
    await queryInterface.addColumn("locations", "status", { type: DataTypes.STRING(50), allowNull: true }, { transaction });
    await queryInterface.addColumn("instruments", "status", { type: DataTypes.STRING(50), allowNull: true }, { transaction });
    await queryInterface.addColumn("instrument_parts", "status", { type: DataTypes.STRING(50), allowNull: true }, { transaction });
    await queryInterface.addColumn("stock_batches", "status", { type: DataTypes.STRING(50), allowNull: true }, { transaction });
    await queryInterface.addColumn("customers", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("suppliers", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("projects", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("locations", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("stock", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("stock_batches", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("instruments", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("instrument_parts", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("batches", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("lots", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("samples", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("tests", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("studies", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });
    await queryInterface.addColumn("specifications", "attachments", { type: DataTypes.JSONB, allowNull: true }, { transaction });

  });
};

export const down = async (queryInterface: QueryInterface): Promise<void> => {
  await queryInterface.sequelize.transaction(async (transaction) => {
    await queryInterface.removeColumn("lims_groups", "modified_by", { transaction });
    await queryInterface.removeColumn("lims_roles", "modified_by", { transaction });
    await queryInterface.removeColumn("lims_users", "modified_by", { transaction });
    await queryInterface.removeColumn("lims_schedulers", "modified_by", { transaction });
    await queryInterface.removeColumn("phrases", "modified_by", { transaction });
    await queryInterface.removeColumn("phrase_entries", "modified_by", { transaction });
    await queryInterface.removeColumn("customers", "modified_by", { transaction });
    await queryInterface.removeColumn("suppliers", "modified_by", { transaction });
    await queryInterface.removeColumn("projects", "modified_by", { transaction });
    await queryInterface.removeColumn("studies", "modified_by", { transaction });
    await queryInterface.removeColumn("locations", "modified_by", { transaction });
    await queryInterface.removeColumn("stock", "modified_by", { transaction });
    await queryInterface.removeColumn("stock_batches", "modified_by", { transaction });
    await queryInterface.removeColumn("aliquots", "modified_by", { transaction });
    await queryInterface.removeColumn("stock_parameters", "modified_by", { transaction });
    await queryInterface.removeColumn("instruments", "modified_by", { transaction });
    await queryInterface.removeColumn("instrument_parts", "modified_by", { transaction });
    await queryInterface.removeColumn("calibration_schedules", "modified_by", { transaction });
    await queryInterface.removeColumn("calibrations", "modified_by", { transaction });
    await queryInterface.removeColumn("inspection_plans", "modified_by", { transaction });
    await queryInterface.removeColumn("inspection_personnel", "modified_by", { transaction });
    await queryInterface.removeColumn("analyses", "modified_by", { transaction });
    await queryInterface.removeColumn("analysis_components", "modified_by", { transaction });
    await queryInterface.removeColumn("test_groups", "modified_by", { transaction });
    await queryInterface.removeColumn("test_group_items", "modified_by", { transaction });
    await queryInterface.removeColumn("specifications", "modified_by", { transaction });
    await queryInterface.removeColumn("spec_limits", "modified_by", { transaction });
    await queryInterface.removeColumn("batches", "modified_by", { transaction });
    await queryInterface.removeColumn("lots", "modified_by", { transaction });
    await queryInterface.removeColumn("samples", "modified_by", { transaction });
    await queryInterface.removeColumn("tests", "modified_by", { transaction });
    await queryInterface.removeColumn("test_windows", "modified_by", { transaction });
    await queryInterface.removeColumn("results", "modified_by", { transaction });
    await queryInterface.renameColumn("customers", "customer_name", "name", { transaction });
    await queryInterface.renameColumn("customers", "email", "contact_email", { transaction });
    await queryInterface.renameColumn("customers", "description", "notes", { transaction });
    await queryInterface.renameColumn("suppliers", "supplier_name", "name", { transaction });
    await queryInterface.renameColumn("suppliers", "email", "contact_email", { transaction });
    await queryInterface.renameColumn("suppliers", "description", "notes", { transaction });
    await queryInterface.renameColumn("projects", "project_id", "name", { transaction });
    await queryInterface.renameColumn("projects", "details", "description", { transaction });
    await queryInterface.renameColumn("locations", "location_name", "name", { transaction });
    await queryInterface.renameColumn("stock", "stock_name", "name", { transaction });
    await queryInterface.renameColumn("instruments", "type", "description", { transaction });
    await queryInterface.renameColumn("instrument_parts", "part_id", "part_number", { transaction });
    await queryInterface.renameColumn("lots", "lot_id", "lot_number", { transaction });
    await queryInterface.renameColumn("samples", "sample_id", "sample_number", { transaction });
    await queryInterface.renameColumn("batches", "batch_id", "batch_number", { transaction });
    await queryInterface.renameColumn("studies", "details", "description", { transaction });
    await queryInterface.removeColumn("calibrations", "status", { transaction });
    await queryInterface.removeColumn("locations", "status", { transaction });
    await queryInterface.removeColumn("instruments", "status", { transaction });
    await queryInterface.removeColumn("instrument_parts", "status", { transaction });
    await queryInterface.removeColumn("stock_batches", "status", { transaction });
    await queryInterface.removeColumn("customers", "attachments", { transaction });
    await queryInterface.removeColumn("suppliers", "attachments", { transaction });
    await queryInterface.removeColumn("projects", "attachments", { transaction });
    await queryInterface.removeColumn("locations", "attachments", { transaction });
    await queryInterface.removeColumn("stock", "attachments", { transaction });
    await queryInterface.removeColumn("stock_batches", "attachments", { transaction });
    await queryInterface.removeColumn("instruments", "attachments", { transaction });
    await queryInterface.removeColumn("instrument_parts", "attachments", { transaction });
    await queryInterface.removeColumn("batches", "attachments", { transaction });
    await queryInterface.removeColumn("lots", "attachments", { transaction });
    await queryInterface.removeColumn("samples", "attachments", { transaction });
    await queryInterface.removeColumn("tests", "attachments", { transaction });
    await queryInterface.removeColumn("studies", "attachments", { transaction });
    await queryInterface.removeColumn("specifications", "attachments", { transaction });

  });
};
