export const ADMIN_PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: "VIEW:DASHBOARD",

  // Permission Management
  CREATE_PERMISSION: "CREATE:PERMISSION",
  VIEW_PERMISSION: "VIEW:PERMISSION",
  UPDATE_PERMISSION: "UPDATE:PERMISSION",
  DELETE_PERMISSION: "DELETE:PERMISSION",

  // Role Management
  CREATE_ROLE: "CREATE:ROLE",
  VIEW_ROLE: "VIEW:ROLE",
  UPDATE_ROLE: "UPDATE:ROLE",
  DELETE_ROLE: "DELETE:ROLE",

  // User Management
  CREATE_USER: "CREATE:USER",
  VIEW_USER: "VIEW:USER",
  UPDATE_USER: "UPDATE:USER",
  DELETE_USER: "DELETE:USER",

  // Department Management
  CREATE_DEPARTMENT: "CREATE:DEPARTMENT",
  VIEW_DEPARTMENT: "VIEW:DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE:DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE:DEPARTMENT",

  // Designation Management
  CREATE_DESIGNATION: "CREATE:DESIGNATION",
  VIEW_DESIGNATION: "VIEW:DESIGNATION",
  UPDATE_DESIGNATION: "UPDATE:DESIGNATION",
  DELETE_DESIGNATION: "DELETE:DESIGNATION",

  // Location Management
  CREATE_LOCATION: "CREATE:LOCATION",
  VIEW_LOCATION: "VIEW:LOCATION",
  UPDATE_LOCATION: "UPDATE:LOCATION",
  DELETE_LOCATION: "DELETE:LOCATION",

  // Admin permissions
  OPERATE_ALL: "OPERATE:ALL"
};

export const GXP_PERMISSIONS = {
  CREATE_PERMISSION: "GXP:CREATE:PERMISSION",
  VIEW_PERMISSION: "GXP:VIEW:PERMISSION",
  UPDATE_PERMISSION: "GXP:UPDATE:PERMISSION",
  DELETE_PERMISSION: "GXP:DELETE:PERMISSION",

  CREATE_ROLE: "GXP:CREATE:ROLE",
  VIEW_ROLE: "GXP:VIEW:ROLE",
  UPDATE_ROLE: "GXP:UPDATE:ROLE",
  DELETE_ROLE: "GXP:DELETE:ROLE",

  CREATE_USER: "GXP:CREATE:USER",
  VIEW_USER: "GXP:VIEW:USER",
  UPDATE_USER: "GXP:UPDATE:USER",
  DELETE_USER: "GXP:DELETE:USER",

  CREATE_ASSIGNMENT_GROUP: "GXP:CREATE:ASSIGNMENT_GROUP",
  VIEW_ASSIGNMENT_GROUP: "GXP:VIEW:ASSIGNMENT_GROUP",
  UPDATE_ASSIGNMENT_GROUP: "GXP:UPDATE:ASSIGNMENT_GROUP",
  DELETE_ASSIGNMENT_GROUP: "GXP:DELETE:ASSIGNMENT_GROUP",

  CREATE_WORKFLOW: "GXP:CREATE:WORKFLOW",
  VIEW_WORKFLOW: "GXP:VIEW:WORKFLOW",
  UPDATE_WORKFLOW: "GXP:UPDATE:WORKFLOW",
  DELETE_WORKFLOW: "GXP:DELETE:WORKFLOW",

  CREATE_ENVIRONMENT: "GXP:CREATE:ENVIRONMENT",
  VIEW_ENVIRONMENT: "GXP:VIEW:ENVIRONMENT",
  UPDATE_ENVIRONMENT: "GXP:UPDATE:ENVIRONMENT",
  DELETE_ENVIRONMENT: "GXP:DELETE:ENVIRONMENT",

  CREATE_SUPPLIERS: "GXP:CREATE:SUPPLIERS",
  VIEW_SUPPLIERS: "GXP:VIEW:SUPPLIERS",
  UPDATE_SUPPLIERS: "GXP:UPDATE:SUPPLIERS",
  DELETE_SUPPLIERS: "GXP:DELETE:SUPPLIERS",

  CREATE_SOFTWARE_MODULES: "GXP:CREATE:SOFTWARE_MODULES",
  VIEW_SOFTWARE_MODULES: "GXP:VIEW:SOFTWARE_MODULES",
  UPDATE_SOFTWARE_MODULES: "GXP:UPDATE:SOFTWARE_MODULES",
  DELETE_SOFTWARE_MODULES: "GXP:DELETE:SOFTWARE_MODULES",

  CREATE_SOFTWARE: "GXP:CREATE:SOFTWARE",
  VIEW_SOFTWARE: "GXP:VIEW:SOFTWARE",
  UPDATE_SOFTWARE: "GXP:UPDATE:SOFTWARE",
  DELETE_SOFTWARE: "GXP:DELETE:SOFTWARE",

  CREATE_SERVICE_REQUEST: "GXP:CREATE:SERVICE_REQUEST",
  VIEW_SERVICE_REQUEST: "GXP:VIEW:SERVICE_REQUEST",
  UPDATE_SERVICE_REQUEST: "GXP:UPDATE:SERVICE_REQUEST",
  DELETE_SERVICE_REQUEST: "GXP:DELETE:SERVICE_REQUEST"
};

/**
 * LIMS permissions. Same `AREA:ACTION:ENTITY` shape as GXP so `hasPermission`
 * and the OPERATE:ALL wildcard work unchanged.
 */
export const LIMS_PERMISSIONS = {
  // Lab Access
  CREATE_USER: "LIMS:CREATE:USER",
  VIEW_USER: "LIMS:VIEW:USER",
  UPDATE_USER: "LIMS:UPDATE:USER",
  DELETE_USER: "LIMS:DELETE:USER",

  CREATE_ROLE: "LIMS:CREATE:ROLE",
  VIEW_ROLE: "LIMS:VIEW:ROLE",
  UPDATE_ROLE: "LIMS:UPDATE:ROLE",
  DELETE_ROLE: "LIMS:DELETE:ROLE",

  CREATE_GROUP: "LIMS:CREATE:GROUP",
  VIEW_GROUP: "LIMS:VIEW:GROUP",
  UPDATE_GROUP: "LIMS:UPDATE:GROUP",
  DELETE_GROUP: "LIMS:DELETE:GROUP",

  // Lab Setup — master data
  CREATE_PROJECT: "LIMS:CREATE:PROJECT",
  VIEW_PROJECT: "LIMS:VIEW:PROJECT",
  UPDATE_PROJECT: "LIMS:UPDATE:PROJECT",
  DELETE_PROJECT: "LIMS:DELETE:PROJECT",

  CREATE_STUDY: "LIMS:CREATE:STUDY",
  VIEW_STUDY: "LIMS:VIEW:STUDY",
  UPDATE_STUDY: "LIMS:UPDATE:STUDY",
  DELETE_STUDY: "LIMS:DELETE:STUDY",

  CREATE_SUPPLIER: "LIMS:CREATE:SUPPLIER",
  VIEW_SUPPLIER: "LIMS:VIEW:SUPPLIER",
  UPDATE_SUPPLIER: "LIMS:UPDATE:SUPPLIER",
  DELETE_SUPPLIER: "LIMS:DELETE:SUPPLIER",

  CREATE_CUSTOMER: "LIMS:CREATE:CUSTOMER",
  VIEW_CUSTOMER: "LIMS:VIEW:CUSTOMER",
  UPDATE_CUSTOMER: "LIMS:UPDATE:CUSTOMER",
  DELETE_CUSTOMER: "LIMS:DELETE:CUSTOMER",

  CREATE_LOCATION: "LIMS:CREATE:LOCATION",
  VIEW_LOCATION: "LIMS:VIEW:LOCATION",
  UPDATE_LOCATION: "LIMS:UPDATE:LOCATION",
  DELETE_LOCATION: "LIMS:DELETE:LOCATION",

  CREATE_STOCK: "LIMS:CREATE:STOCK",
  VIEW_STOCK: "LIMS:VIEW:STOCK",
  UPDATE_STOCK: "LIMS:UPDATE:STOCK",
  DELETE_STOCK: "LIMS:DELETE:STOCK",

  CREATE_PARAMETER: "LIMS:CREATE:PARAMETER",
  VIEW_PARAMETER: "LIMS:VIEW:PARAMETER",
  UPDATE_PARAMETER: "LIMS:UPDATE:PARAMETER",
  DELETE_PARAMETER: "LIMS:DELETE:PARAMETER",

  CREATE_STOCK_BATCH: "LIMS:CREATE:STOCK_BATCH",
  VIEW_STOCK_BATCH: "LIMS:VIEW:STOCK_BATCH",
  UPDATE_STOCK_BATCH: "LIMS:UPDATE:STOCK_BATCH",
  DELETE_STOCK_BATCH: "LIMS:DELETE:STOCK_BATCH",

  CREATE_ALIQUOT: "LIMS:CREATE:ALIQUOT",
  VIEW_ALIQUOT: "LIMS:VIEW:ALIQUOT",
  UPDATE_ALIQUOT: "LIMS:UPDATE:ALIQUOT",
  DELETE_ALIQUOT: "LIMS:DELETE:ALIQUOT",

  CREATE_INSTRUMENT: "LIMS:CREATE:INSTRUMENT",
  VIEW_INSTRUMENT: "LIMS:VIEW:INSTRUMENT",
  UPDATE_INSTRUMENT: "LIMS:UPDATE:INSTRUMENT",
  DELETE_INSTRUMENT: "LIMS:DELETE:INSTRUMENT",

  CREATE_INSTRUMENT_PART: "LIMS:CREATE:INSTRUMENT_PART",
  VIEW_INSTRUMENT_PART: "LIMS:VIEW:INSTRUMENT_PART",
  UPDATE_INSTRUMENT_PART: "LIMS:UPDATE:INSTRUMENT_PART",
  DELETE_INSTRUMENT_PART: "LIMS:DELETE:INSTRUMENT_PART",

  CREATE_CALIBRATION: "LIMS:CREATE:CALIBRATION",
  VIEW_CALIBRATION: "LIMS:VIEW:CALIBRATION",
  UPDATE_CALIBRATION: "LIMS:UPDATE:CALIBRATION",
  DELETE_CALIBRATION: "LIMS:DELETE:CALIBRATION",

  CREATE_INSPECTION_PLAN: "LIMS:CREATE:INSPECTION_PLAN",
  VIEW_INSPECTION_PLAN: "LIMS:VIEW:INSPECTION_PLAN",
  UPDATE_INSPECTION_PLAN: "LIMS:UPDATE:INSPECTION_PLAN",
  DELETE_INSPECTION_PLAN: "LIMS:DELETE:INSPECTION_PLAN",

  CREATE_ANALYSIS: "LIMS:CREATE:ANALYSIS",
  VIEW_ANALYSIS: "LIMS:VIEW:ANALYSIS",
  UPDATE_ANALYSIS: "LIMS:UPDATE:ANALYSIS",
  DELETE_ANALYSIS: "LIMS:DELETE:ANALYSIS",

  CREATE_TEST_GROUP: "LIMS:CREATE:TEST_GROUP",
  VIEW_TEST_GROUP: "LIMS:VIEW:TEST_GROUP",
  UPDATE_TEST_GROUP: "LIMS:UPDATE:TEST_GROUP",
  DELETE_TEST_GROUP: "LIMS:DELETE:TEST_GROUP",

  CREATE_SPECIFICATION: "LIMS:CREATE:SPECIFICATION",
  VIEW_SPECIFICATION: "LIMS:VIEW:SPECIFICATION",
  UPDATE_SPECIFICATION: "LIMS:UPDATE:SPECIFICATION",
  DELETE_SPECIFICATION: "LIMS:DELETE:SPECIFICATION",

  // C. Lab Executions
  CREATE_BATCH: "LIMS:CREATE:BATCH",
  VIEW_BATCH: "LIMS:VIEW:BATCH",
  UPDATE_BATCH: "LIMS:UPDATE:BATCH",
  DELETE_BATCH: "LIMS:DELETE:BATCH",

  CREATE_LOT: "LIMS:CREATE:LOT",
  VIEW_LOT: "LIMS:VIEW:LOT",
  UPDATE_LOT: "LIMS:UPDATE:LOT",
  DELETE_LOT: "LIMS:DELETE:LOT",

  CREATE_SAMPLE: "LIMS:CREATE:SAMPLE",
  VIEW_SAMPLE: "LIMS:VIEW:SAMPLE",
  UPDATE_SAMPLE: "LIMS:UPDATE:SAMPLE",
  DELETE_SAMPLE: "LIMS:DELETE:SAMPLE",

  CREATE_TEST: "LIMS:CREATE:TEST",
  VIEW_TEST: "LIMS:VIEW:TEST",
  UPDATE_TEST: "LIMS:UPDATE:TEST",
  DELETE_TEST: "LIMS:DELETE:TEST",

  CREATE_RESULT: "LIMS:CREATE:RESULT",
  VIEW_RESULT: "LIMS:VIEW:RESULT",
  UPDATE_RESULT: "LIMS:UPDATE:RESULT",
  DELETE_RESULT: "LIMS:DELETE:RESULT",

  CREATE_SCHEDULER: "LIMS:CREATE:SCHEDULER",
  VIEW_SCHEDULER: "LIMS:VIEW:SCHEDULER",
  UPDATE_SCHEDULER: "LIMS:UPDATE:SCHEDULER",
  DELETE_SCHEDULER: "LIMS:DELETE:SCHEDULER",

  CREATE_PHRASE: "LIMS:CREATE:PHRASE",
  VIEW_PHRASE: "LIMS:VIEW:PHRASE",
  UPDATE_PHRASE: "LIMS:UPDATE:PHRASE",
  DELETE_PHRASE: "LIMS:DELETE:PHRASE"
};

/** Any LIMS Lab Access permission — gates the Lab Access sidebar group. */
export const LIMS_ACCESS_PERMISSIONS = [
  LIMS_PERMISSIONS.CREATE_USER,
  LIMS_PERMISSIONS.VIEW_USER,
  LIMS_PERMISSIONS.UPDATE_USER,
  LIMS_PERMISSIONS.DELETE_USER,
  LIMS_PERMISSIONS.CREATE_ROLE,
  LIMS_PERMISSIONS.VIEW_ROLE,
  LIMS_PERMISSIONS.UPDATE_ROLE,
  LIMS_PERMISSIONS.DELETE_ROLE,
  LIMS_PERMISSIONS.CREATE_GROUP,
  LIMS_PERMISSIONS.VIEW_GROUP,
  LIMS_PERMISSIONS.UPDATE_GROUP,
  LIMS_PERMISSIONS.DELETE_GROUP
];

/** Lab Execution permissions — gates the Lab Executions sidebar group. */
export const LIMS_EXECUTION_PERMISSIONS = Object.entries(LIMS_PERMISSIONS)
  .filter(([key]) => /_(BATCH|LOT|SAMPLE|TEST|RESULT|SCHEDULER)$/.test(key))
  .map(([, value]) => value);

/** Any LIMS master-data permission — gates the Lab Setup sidebar group. */
export const LIMS_SETUP_PERMISSIONS = Object.values(LIMS_PERMISSIONS).filter(
  (permission) =>
    !LIMS_ACCESS_PERMISSIONS.includes(permission) &&
    !LIMS_EXECUTION_PERMISSIONS.includes(permission)
);

export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  USER: "USER"
};

const getRoles = (user?: AuthenticatedUser | null): UserRole[] => {
  if (!user || !user.roles) return [];

  return user.roles;
};

const getPermissions = (user?: AuthenticatedUser | null): string[] =>
  getRoles(user)
    .flatMap((role) => role.permissions ?? [])
    .map((permission) => permission.name);

export const hasPermission = (
  user: AuthenticatedUser | null | undefined,
  permission: string
): boolean => {
  const permissions = getPermissions(user);
  return (
    permissions?.includes(permission) ||
    permissions?.includes(ADMIN_PERMISSIONS.OPERATE_ALL)
  );
};

export const hasRole = (
  user: AuthenticatedUser | null | undefined,
  role: string
): boolean => {
  const userRoles = getRoles(user).map((role) => role.name);
  return userRoles.includes(role);
};

export const hasAnyRole = (
  user: AuthenticatedUser | null | undefined,
  roles: string[]
): boolean => {
  const userRoles = getRoles(user).map((role) => role.name);
  return roles.some((role) => userRoles.includes(role));
};

export const hasAnyPermission = (
  user: AuthenticatedUser | null | undefined,
  permissions: string[]
): boolean => {
  const userPermissions = getPermissions(user);
  const hasPermission = permissions.some(
    (permission) =>
      userPermissions?.includes(permission) ||
      userPermissions?.includes(ADMIN_PERMISSIONS.OPERATE_ALL)
  );
  return hasPermission;
};

export const getUserPermissions = (
  user: AuthenticatedUser | null | undefined
): string[] => {
  return getPermissions(user);
};

export const getUserRoles = (
  user: AuthenticatedUser | null | undefined
): string[] => {
  return getRoles(user).map((role) => role.name);
};
import type { AuthenticatedUser, UserRole } from "@/types/common.types";
